# Generated by Django 5.1.3 on 2024-11-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeecustomfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecustomfield',
            name='is_active',
        ),
    ]
